
apiVersion: v1
kind: Service
metadata:
  name: fww-core
  labels:
    app: fww-core
  annotations:
    linkerd.io/inject: enabled # Enable Linkerd injection
spec:
  ports:
    - name: http
      port: 80
      targetPort: 8080
  selector:
    app: fww-core
